package PersonaApp;

/**
* PersonaApp/estadoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* domingo 27 de mayo de 2018 06:22:43 PM COT
*/

public final class estadoHolder implements org.omg.CORBA.portable.Streamable
{
  public PersonaApp.estado value = null;

  public estadoHolder ()
  {
  }

  public estadoHolder (PersonaApp.estado initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PersonaApp.estadoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PersonaApp.estadoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PersonaApp.estadoHelper.type ();
  }

}
