package PersonaApp;


/**
* PersonaApp/estadoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* domingo 27 de mayo de 2018 06:22:43 PM COT
*/

public interface estadoOperations 
{
  boolean insertarEstado (int id, String nombre);
  String consultarEstado (int id);
  boolean eliminarEstado (int nombre);
  boolean actualizarEstado (int id, String nombre);
  String listarEstado ();
  void shutdawn ();
} // interface estadoOperations
