package PersonaApp;


/**
* PersonaApp/generoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* domingo 27 de mayo de 2018 06:22:43 PM COT
*/

public interface generoOperations 
{
  boolean insertarGenero (int id, String nombre);
  String consultarGenero (int id);
  boolean eliminarGenero (int nombre);
  boolean actualizarGenero (int id, String nombre);
  String listarGenero ();
  void shutdawn ();
} // interface generoOperations
