package PersonaApp;


/**
* PersonaApp/persona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 28 de mayo de 2018 07:05:09 PM COT
*/

public interface persona extends personaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface persona
