package PersonaApp;


/**
* PersonaApp/personaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 28 de mayo de 2018 07:05:09 PM COT
*/

public interface personaOperations 
{
  boolean insertarPersona (int cedula, String nombre, String apellido, String genero, int edad, String estado);
  String consultarPersona (int cedula);
  boolean eliminarPersona (int cedula);
  boolean actualizarPersona (int cedula, String nombre, String apellido, String genero, int edad, String estado);
  String listarPersona ();
  void shutdawn ();
} // interface personaOperations
