import javax.swing.JOptionPane;


public class GeneroFrm extends javax.swing.JFrame {


    /**
     * Creates new form GeneroFrm
     */
    public GeneroFrm() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnMenu = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        lblPersona = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnInsertarGenero = new javax.swing.JButton();
        btnListarGenero = new javax.swing.JButton();
        btnConsultarGenero = new javax.swing.JButton();
        btnActualizarGenero = new javax.swing.JButton();
        btnEliminarGenero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnMenu.setBackground(new java.awt.Color(0, 0, 204));
        BtnMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnMenu.setText("Menú");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        BtnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        lblPersona.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPersona.setText("ID:");

        lblNombres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombres.setText("Nombre:");

        btnInsertarGenero.setBackground(new java.awt.Color(0, 153, 51));
        btnInsertarGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarGenero.setText("Insertar");
        btnInsertarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarGeneroActionPerformed(evt);
            }
        });

        btnListarGenero.setBackground(new java.awt.Color(255, 255, 0));
        btnListarGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListarGenero.setText("Listar");
        btnListarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarGeneroActionPerformed(evt);
            }
        });

        btnConsultarGenero.setBackground(new java.awt.Color(0, 51, 255));
        btnConsultarGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarGenero.setText("Consultar");
        btnConsultarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarGeneroActionPerformed(evt);
            }
        });

        btnActualizarGenero.setBackground(new java.awt.Color(204, 0, 204));
        btnActualizarGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizarGenero.setText("Actualizar");
        btnActualizarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarGeneroActionPerformed(evt);
            }
        });

        btnEliminarGenero.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarGenero.setText("Eliminar");
        btnEliminarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGeneroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Genero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(BtnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersona)
                            .addComponent(lblNombres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txtNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnActualizarGenero)
                                .addGap(28, 28, 28)
                                .addComponent(btnEliminarGenero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertarGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListarGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultarGenero))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersona)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarGenero)
                    .addComponent(btnListarGenero)
                    .addComponent(btnConsultarGenero))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarGenero)
                    .addComponent(btnActualizarGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir)
                    .addComponent(BtnMenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        InicioFrm verFormularioInicio = new InicioFrm();
        verFormularioInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void btnInsertarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarGeneroActionPerformed

        Persona per = new Persona();

        boolean resultado = per.insertarGenero(Integer.parseInt(txtId.getText()),txtNombre.getText());

        if(resultado==true){
            JOptionPane.showMessageDialog(null, "Los Datos Se Insertaron");
        }else{
            JOptionPane.showMessageDialog(null, "Los Datos No Se Insertaron");
        }
    }//GEN-LAST:event_btnInsertarGeneroActionPerformed

    private void btnListarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarGeneroActionPerformed

        Persona per = new Persona();
        String lista = per.listarGenero();
        JOptionPane.showMessageDialog(null, lista);

    }//GEN-LAST:event_btnListarGeneroActionPerformed

    private void btnConsultarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarGeneroActionPerformed

        Persona per = new Persona();
        int id = Integer.parseInt(txtId.getText());
        String lista = per.consultarGenero(id);
        JOptionPane.showMessageDialog(null, lista);

    }//GEN-LAST:event_btnConsultarGeneroActionPerformed

    private void btnActualizarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarGeneroActionPerformed

        Persona per = new Persona();

        boolean resultado = per.actualizarGenero(Integer.parseInt(txtId.getText()),
            txtNombre.getText());
        if(resultado==true){
            JOptionPane.showMessageDialog(null, "Los Datos Se Actualizaron");
        }else{
            JOptionPane.showMessageDialog(null, "Los Datos No Actualizaron");
        }
    }//GEN-LAST:event_btnActualizarGeneroActionPerformed

    private void btnEliminarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGeneroActionPerformed

        Persona per = new Persona();
        boolean resultado = per.eliminarGenero(Integer.parseInt(txtId.getText()));

        if(resultado==true){
            JOptionPane.showMessageDialog(null, "Los Datos Se Eliminaron");
        }else{
            JOptionPane.showMessageDialog(null, "Los Datos No Se Insertaron");
        }

    }//GEN-LAST:event_btnEliminarGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneroFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GeneroFrm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton btnActualizarGenero;
    private javax.swing.JButton btnConsultarGenero;
    private javax.swing.JButton btnEliminarGenero;
    private javax.swing.JButton btnInsertarGenero;
    private javax.swing.JButton btnListarGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
